### ISSUE TITLE
Pure Python Whl

### ISSUE THREAD

**Issue by JakobWyatt-VGW** [denismr/incremental-ks#2]
Would you be willing to accept a PR making the Pure Python implementation easily turned into an installable .whl?

**Comment by denismr** [comment]
I'm really sorry for the very late response.

Thing is.. To my understanding, the pure python version is more of an "academic" implementation, and I strongly recommend _against_ using it. There is a very considerable performance penalty, and the algorithm as whole lose its appeal in many scenarios with not so big samples where it would be easier and perhaps even faster to simply use `ks_2samp`.

That being said, if the PR is rather small, I have no problem accepting it at all (and thanks for offering this). More choice is always welcome.
